Cadeia B
Cadeia ; Numero de aminoacidos da cadeia ; Numero de ligacoes dissulfidicas  : (a1,i5,i5)
B  160    0
Aminoacidos envolvidos nas ligacoes dissulfidicas  : n(i4,i4,/)
Sequencia de aminoacidos da cadeia A  : n(10(a5,1x),/)
GLYI  ILE   PRO   LYS   TRP   ARG   LYS   THR   HISE  LEU  
THR   TYR   ARG   ILE   VAL   ASN   TYR   THR   PRO   ASP  
LEU   PRO   LYS   ASP   ALA   VAL   ASP   SER   ALA   VAL  
GLU   LYS   ALA   LEU   LYS   VAL   TRP   GLU   GLU   VAL  
THR   PRO   LEU   THR   PHE   SER   ARG   LEU   TYR   GLU  
GLY   GLU   ALA   ASP   ILE   MET   ILE   SER   PHE   ALA  
VAL   ARG   GLU   HISD  GLY   ASP   PHE   TYR   PRO   PHE  
ASP   GLY   PRO   GLY   ASN   VAL   LEU   ALA   HISD  ALA  
TYR   ALA   PRO   GLY   PRO   GLY   ILE   ASN   GLY   ASP  
ALA   HISE  PHE   ASP   ASP   ASP   GLU   GLN   TRP   THR  
LYS   ASP   THR   THR   GLY   THR   ASN   LEU   PHE   LEU  
VAL   ALA   ALA   HISD  GLU   ILE   GLY   HISD  SER   LEU  
GLY   LEU   PHE   HISD  SER   ALA   ASN   THR   GLU   ALA  
LEU   MET   TYR   PRO   LEU   TYR   HISD  SER   LEU   THR  
ASP   LEU   THR   ARG   PHE   ARG   LEU   SER   GLN   ASP  
ASP   ILE   ASN   GLY   ILE   GLN   SER   LEU   TYR   GLYT 
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                     

